### ISSUE TITLE
Discord Token Problems

### ISSUE THREAD

**Issue by nanocraftmr** [Fabian9799/PhilipsHue-Discord-Bot#8]
im trying to get the bot to work, but eventho the token is entered correctly it. this is the error i get:
pi@raspberrypi:~/PhilipsHue-Discord-Bot $ npm start

> huebot@1.0.0 start
> node ./src/index.js

/home/pi/PhilipsHue-Discord-Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:133
    const invalidToken = new DJSError(WSCodes[4004]);
                         ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (/home/pi/PhilipsHue-Discord-Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:133:26)
    at Client.login (/home/pi/PhilipsHue-Discord-Bot/node_modules/discord.js/src/client/Client.js:223:21)
    at async /home/pi/PhilipsHue-Discord-Bot/src/index.js:14:3 {
  [Symbol(code)]: 'TOKEN_INVALID'
}

**Comment by Fabian9799** [comment]
How does your `.env` file look like? (don't share the actual token)

**Comment by nanocraftmr** [comment]
> How does your `.env` file look like? (don't share the actual token)

TOKEN=<MTA4O...>
USER=<nan...>
BEARER=Bearer <jfjEgFYDXuy3s...>

**Comment by Fabian9799** [comment]
You need to remove the `<` and `>` in every line

**Comment by nanocraftmr** [comment]
the bot now works in discord, but the lights dont turn off. In the CLIP API Debugger my lights can be turnt on and off but over dc not. idk what could be the problem now. do i need to press the button before starting the programm or am i missing something else?

**Comment by Fabian9799** [comment]
Since I created the bot a while ago you might need to enable the "message content intent" on the discord developer page for your bot for it to be able to read messages on the server
![image](https://user-images.githubusercontent.com/19490891/227723697-e11dbe8e-5325-47e3-b7a3-c8278dba3078.png)

**Comment by nanocraftmr** [comment]
ok the bot now also funktions on servers and i got this error:

HueBot#5174 has logged in.
Error: Request failed with status code 504
    at createError (/home/pi/PhilipsHue-Discord-Bot/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/PhilipsHue-Discord-Bot/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/PhilipsHue-Discord-Bot/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {
    url: 'https://api.meethue.com/bridge/pi/lights/1/state',
    method: 'put',
    data: '{"on":true}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'Bearer svAqjiASCFBVoDvZsAOGOj5Xm8EG',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 11
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 11,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.meethue.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.meethue.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 91,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'PUT /bridge/pi/lights/1/state HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'Authorization: Bearer svAqjiASCFBVoDvZsAOGOj5Xm8EG\r\n' +
      'User-Agent: axios/0.21.4\r\n' +
      'Content-Length: 11\r\n' +
      'Host: api.meethue.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'PUT',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/bridge/pi/lights/1/state',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 504,
      statusMessage: 'Gateway Timeout',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.meethue.com/bridge/pi/lights/1/state',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 26,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.meethue.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 11,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.meethue.com/bridge/pi/lights/1/state',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kEndCalled)]: true,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    },
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 504,
    statusText: 'Gateway Timeout',
    headers: {
      date: 'Sat, 25 Mar 2023 14:37:11 GMT',
      'content-type': 'text/plain; charset=utf-8',
      'content-length': '15',
      connection: 'close',
      server: 'nginx',
      'access-control-allow-origin': '*',
      'access-control-allow-methods': 'POST, GET, OPTIONS, PUT, DELETE',
      'access-control-allow-headers': 'X-Token, X-Bridge, Content-Type',
      'x-message-id': '147872627',
      etag: 'W/"f-PdYQLWjSnEAE7Ghe7kCkXnLz2wQ"',
      'x-response-time': '5003.121ms',
      via: '1.1 google',
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'
    },
    config: {
      url: 'https://api.meethue.com/bridge/pi/lights/1/state',
      method: 'put',
      data: '{"on":true}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      transitional: [Object]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 11,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'PUT /bridge/pi/lights/1/state HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Bearer svAqjiASCFBVoDvZsAOGOj5Xm8EG\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Content-Length: 11\r\n' +
        'Host: api.meethue.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'PUT',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/bridge/pi/lights/1/state',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.meethue.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    data: 'Gateway Timeout'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by Fabian9799** [comment]
I deleted your commend since you accidentally left your token in it.
Looks like the request is timing out for some reason. Might be better to debug it through screenshare at this point. Feel free to message me on discord at Fabian#9799

**Comment by Fabian9799** [comment]
Closed, had to change the token
